Feat/readme
EDMdesigner/plugin-interface pull request #24
Opened 2022-05-25 10:09 UTC by arnolduis

2022-05-31 07:54 UTC, lacee677 requested changes

2022-05-31 07:54 UTC, lacee677 commented on README.md
> +In the provided interface you will reach the following props:
Talán kicsit érthetőbb.

```
In the returned object you will get the following properties
```

2022-05-31 07:54 UTC, lacee677 commented on README.md
> +```
```suggestion
**Animations**

The `show` can be called with the following parameters:

```js
show({ x = "-100vw", y = "0px", opacity = 0.5, scale = 1, time = 500 })
```
```

2022-05-31 07:54 UTC, lacee677 commented on README.md
> +```
kell egy üres sor az animations után hogy ne fusson össze a szöveg

2022-05-31 07:54 UTC, lacee677 commented on README.md
> +The `show` function provides an easy way to customize your show animation. With the provided parameters, you can set the default hidden state, described by coordinates, opacity, and scale of the plug
```suggestion
The `show` function provides an easy way to customize your show animation. With the provided parameters, you can set the default hidden state, described by coordinates, opacity, and scale of the plugin, along with the time of the animation. When the function is called, the plugin will move to a fullscreen view from that hidden position. The animation uses the `translate3d` css function. Likewise, the `hide` function moves the plugin back to its set hidden state.
```

2022-05-31 07:54 UTC, lacee677 commented on README.md
> +}
```suggestion
{
	_container: HTMLElement,
	methods: Object,
	destroy: Function,
}
```

2022-05-31 07:54 UTC, lacee677 commented on README.md
> +- **validator:** Is a function that will run when the provided `data`, `settings` and `hooks` arrive from the from the parent side
```suggestion
- **validator:** Is a function that will run when the provided `data`, `settings` and `hooks` arrive from the parent side
```

2022-05-31 07:54 UTC, lacee677 commented on README.md
> +In the provided interface you will reach the following props:
Talán kicsit érthetőbb.

```
In the returned object you will get the following properties
```

2022-05-31 07:54 UTC, lacee677 commented on README.md
> +The providePlugin function should resolve to an object containing these fields:
Talán kicsit érthetőbb.

```
In the returned object you will get the following properties
```

2022-05-31 07:54 UTC, lacee677 commented on README.md
> +- **methods:** through the methods object you can reach the plugins declared methods
```suggestion
- **methods:** through the methods object you can reach the plugin's declared methods
```

2022-05-31 07:54 UTC, lacee677 commented on README.md
> +- **methods:** through the methods object you can reach the plugins declared methods
```suggestion
- **methods:** through the methods object you can reach the plugin's declared methods
```

2022-05-31 07:54 UTC, lacee677 commented on README.md
> +<script src="main.js"></script>
ezt az example-t ki is próbáltad?
mert elvileg itt ez kell hogy rendesen menjen:
```suggestion
<script src="main.js" type="module"></script>
```

2022-05-31 07:54 UTC, lacee677 commented on README.md
> +});
```suggestion
import { initFullscreenPlugin } from "@chamaileon-sdk/plugin-interface";
const myPlugin = await initFullscreenPlugin(
{
	data: {},
	settings: {
		buttons: {
			header: [],
		},
	},
	hooks: {
		close: () => {
			myPlugin.hide();
		},
		onHeaderButtonClicked: ({ buttonId }) => {
			console.info("Button clicked: " + buttonId);
		},
	},
},
{
	id: "myPlugin",
	src: "http://route/to/my/plugin/html",
	parentElem: "#pluginWrapper",
	beforeInit: () => {},
	timeout: 15000,
});
```

2022-05-31 07:54 UTC, lacee677 commented on README.md
> +<script src="plugin.js"></script>
ugyanaz a kérdés mint a másik script tag-nál

2022-05-31 07:54 UTC, lacee677 commented on README.md
> +}
```suggestion
function updateData(data = {}) {
	console.log(data);
}
```

2022-05-31 07:54 UTC, lacee677 commented on README.md
> +}
```suggestion
function updateSettings(settings = {}) {
	console.log(settings);
}
```

2022-06-08 06:20 UTC, lacee677 requested changes

2022-06-08 06:20 UTC, lacee677 commented on README.md
> +In the provided interface you will reach the following props:
ez még mindig valid

2022-06-08 06:20 UTC, lacee677 commented on src/initFullscreenPlugin.js
> +			// container.style.transform = hiddenPosition;
ezt töröld ki nyugodtan

2022-06-08 06:20 UTC, lacee677 commented on src/initFullscreenPlugin.js
> +		window.requestAnimationFrame(()=>{
ezt kétlem hogy átengedi a linter, nézd meg kérlek hogy nincs-e lint error a repóban

2022-06-08 06:20 UTC, lacee677 commented on src/initFullscreenPlugin.js
> +			container.style.display = "block"
```suggestion
			container.style.display = "block";
```

2022-06-08 10:14 UTC, lacee677 requested changes

2022-06-08 10:14 UTC, lacee677 commented on README.md
> + static-server -c "*" -zp 10101
```suggestion
You can run the examples, with static server

```js
static-server -c "*" -zp 8080
```

```

2022-06-08 10:22 UTC, lacee677 approved these changes

2022-06-08 11:02 UTC, gyulanemeth requested changes

2022-06-08 11:40 UTC, gyulanemeth approved these changes

2022-06-08 11:44 UTC, merged